### ISSUE TITLE
Incompatibility with p1xel8ted's "Where's My Storage Mod"

### ISSUE THREAD

**Issue by Kreestijan** [AzeTheGreat/GYK-Mods#2] opened 2023-07-07 23:22 UTC
Found out that after installing this mod, the "Where's My Storage Mod" stopped functioning completely.

Link to said mod: https://www.nexusmods.com/graveyardkeeper/mods/62

**Comment by AzeTheGreat** [comment] 2023-07-08 00:21
Could you please elaborate on, "stopped functioning completely"?  What symptoms are you seeing?  If you hit F1 to open the configuration manager, do the WMS options show there?

There is essentially 0 chance this is caused by this mod.  There's just no mechanism for it and I was just able to verify compatibility locally.

**Comment by Kreestijan** [comment] 2023-07-08 07:15
I attempted to reproduce this once more and was unsuccessful. I've attached a list of the mods I used to reproduce this yesterday.
I figured this mod shouldn't interfere with the others, given its purpose however it was the only one I added yesterday and the issue happened as soon as I started the game with it. (And was gone after removing it and restarting the game)

The behavior was the following: 

- Player Inventory reverted to its default value
- Had no access to the Trunks when accessing a vendor (Dead Horse Tavern)
- Horadric reached Tier III suddenly (having been Tier I previously) and reverted to Tier I after I removed the mod
- The WMS options did show up in the configuration panel but none were functional, no matter what I set them to

In any case, it's not happening now, definitely something weird going on. Apologies for wasting your time, feel free to close this.

![ModList](https://github.com/AzeTheGreat/GYK-Mods/assets/5724259/9fc437fb-fe9b-4039-bc64-a3c44ad39d51)

**Comment by AzeTheGreat** [comment] 2023-07-08 16:18
I am going to close this for now.

Random, unreproducible loading issues could be caused by a race condition (most likely to be in BepInEx or WMS), mod manager issues (displayed WMS as enabled but disabled it on the backend), or maybe just a one-off localized PC issue.  I'd give this a near zero chance of being anything caused by my code.  Unfortunately, I am not aware of anyone else having similar issues with this software stack.

If you do run into this more, feel free to re-open this issue and provide more info.  This would be very hard to troubleshoot without a reproducible case though.   For the best shot, enable all of the logging options except IL in the BepInEx Configuration Manager settings, and provide the log file if it happens again.

**Closed as completed by AzeTheGreat** 2023-07-08 16:18 UTC
